name: Test zephyr
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/zephyrprojectrtos/zephyr-build:latest
    steps:

      - name: Test
        run: |
          git clone https://github.com/zephyrproject-rtos/zephyr
          cd zephyr
          west build -p auto -b arduino_nano_33_ble samples/hello_world
