name: Test zephyr
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/zephyrprojectrtos/zephyr-build:latest
    steps:

      - name: Test
        run: |
          git checkout https://github.com/zephyrproject-rtos/zephyr
